### ISSUE TITLE
[NON-BUG] Thank you SO MUCH

### ISSUE THREAD

**Issue by elsell** [Thebowers89/FancyCam2#3]
### I apologize for making an issue, but I couldn't find another great way to contact you. 

Thank you SO much for making this plug-in. I just wanted a SIMPLE plugin to orbit around a point. There are so many bloated plugins that get 70% there, but they either don't loop, or they're terribly stuttery. 

Your plugin is buttery smooth and loops infinitely - just what I wanted!!! 

➡️ **Please, if you have some way to donate to your work or buy you some food, please let me know. You saved me from having to build another plug-in this week (and I am very grateful).**

If you're wondering, I'm using the plugin on the server `mc.3411.best` where I am currently 3D Printing whatever people build every 24Hours and then live-streaming the print :) 

Cheers!!!

**Comment by Thebowers89** [comment]
I greatly appreciate your kind words, I completely forgot about this project and I am glad to see someone is enjoying it.
